// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwUVLUvBSu4nWZzerQrfDTfS02SdAe9A',
    appId: '1:500274860238:web:a2c5ad1d5a3aa8a4ad009f',
    messagingSenderId: '500274860238',
    projectId: 'fir-bookmark-73ffc',
    authDomain: 'fir-bookmark-73ffc.firebaseapp.com',
    storageBucket: 'fir-bookmark-73ffc.appspot.com',
    measurementId: 'G-YQ3D2BYQ78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVuGpNs_8fAx8B-impzcEMM62CDuLO06U',
    appId: '1:500274860238:android:30657d5fe491c885ad009f',
    messagingSenderId: '500274860238',
    projectId: 'fir-bookmark-73ffc',
    storageBucket: 'fir-bookmark-73ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3xM0bLUUVuWRHBTqJ4wYmsIbiuIeXvSQ',
    appId: '1:500274860238:ios:a330469ee145d8b6ad009f',
    messagingSenderId: '500274860238',
    projectId: 'fir-bookmark-73ffc',
    storageBucket: 'fir-bookmark-73ffc.appspot.com',
    iosBundleId: 'com.example.firebaseBookmark',
  );
}
